# Generated by Django 5.0.3 on 2024-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сайта')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Инстаграм')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание для SEO')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова для SEO')),
                ('og_description', models.CharField(max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
