# Generated by Django 5.0.3 on 2024-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasitemodel',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Главные настройки'},
        ),
        migrations.AddField(
            model_name='datasitemodel',
            name='brand_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
