# Generated by Django 5.0.3 on 2024-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_site', '0003_pricemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasitemodel',
            name='address',
            field=models.TextField(default=1, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
