# Generated by Django 5.0.3 on 2024-03-27 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickersmodule',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='clickersmodule',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 27, 16, 4, 0, 58193), null=True, verbose_name='Дата'),
        ),
    ]
