# Generated by Django 5.0.3 on 2024-03-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_clickersmodule_ip_alter_clickersmodule_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickersmodule',
            options={'verbose_name': 'Клик', 'verbose_name_plural': 'Клики'},
        ),
        migrations.AddField(
            model_name='clickersmodule',
            name='utm',
            field=models.CharField(blank=True, max_length=10000, verbose_name='utm метки'),
        ),
        migrations.AlterField(
            model_name='clickersmodule',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 27, 16, 20, 53, 18583), null=True, verbose_name='Дата'),
        ),
    ]
