# Generated by Django 5.0.3 on 2024-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_clickersmodule_options_clickersmodule_utm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickersmodule',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
