# Generated by Django 5.0.3 on 2024-03-20 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 20, 17, 40, 9, 469137), null=True),
        ),
    ]
