# Generated by Django 5.0.3 on 2024-03-23 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordermodel_comment_alter_ordermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('T', 'Треш'), ('P', 'Перезвонить'), ('A', 'Подтвержден'), ('R', 'Отклонён')], db_index=True, default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='comment',
            field=models.CharField(blank=True, max_length=1255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 24, 1, 10, 30, 508469), null=True),
        ),
    ]
