# Generated by Django 5.0.3 on 2024-03-23 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordermodel_status_alter_ordermodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 24, 1, 11, 33, 806055), null=True),
        ),
    ]
