# Generated by Django 5.0.3 on 2024-03-24 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_ordermodel_date_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 24, 10, 47, 59, 116255), null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('T', 'Треш'), ('P', 'Перезвонить'), ('A', 'Подтвержден'), ('R', 'Отклонён'), ('N', 'Новый')], db_index=True, default='N', max_length=1, verbose_name='Статус'),
        ),
    ]
