# Generated by Django 5.0.3 on 2024-03-25 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_ordermodel_ip_alter_ordermodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='url',
            field=models.CharField(blank=True, max_length=1255, null=True, verbose_name='UTM метка'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 25, 18, 43, 56, 323130), null=True),
        ),
    ]
