# Generated by Django 5.0.3 on 2024-03-27 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_ordermodel_url_alter_ordermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 27, 15, 59, 50, 860267), null=True, verbose_name='Дата'),
        ),
    ]
