# Generated by Django 5.0.3 on 2024-03-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_ordermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 27, 16, 20, 53, 16583), null=True, verbose_name='Дата'),
        ),
    ]
